#!/bin/bash

files=$(git diff --cached --name-status | awk '$1 != "D" { print $2 }')
lc_files=`echo $files | tr '[A-Z]' '[a-z]'`
if [[ $lc_files != *".php"* ]]; then
    exit 0
fi

PHPCS=$( which phpcs )

if [ ! -f "$PHPCS" ]; then
    # PHPCS isn't installed, skip.
    exit 0;
fi

echo -en "\033[1;33mWould you like to run PHPCS? [y|n] \033[0m"
echo -en "\033[1m"
read -n 1 -r < /dev/tty
echo -en "\033[0m"
echo ""
if echo $REPLY | grep -E '^[Yy]$' > /dev/null; then
    echo "Running PHPCS on $files..."
    $PHPCS $files
    PHPCSRETURN=$?
    if [ ! $PHPCSRETURN -eq 0 ]; then
        echo -en "\033[1;33mPHPCS has failed, allow commit anyway? [y|n] \033[0m"
        echo -en "\033[1m"
        read -n 1 -r < /dev/tty
        echo -en "\033[0m"
        echo ""
        if echo $REPLY | grep -E '^[Yy]$' > /dev/null; then
            echo -e "\033[0;32mContinuing with commit...\033[0m"
            exit 0
        else
            echo -e "\033[0;32mCanceling commit...\033[0m"
            exit $PHPCSRETURN
        fi
    fi
    echo -e "\033[0;32mPHPCS has completed successfully...\033[0m"
fi
exit 0