#!/bin/bash

exit 1;
DIFF=$( git diff --cached HEAD | grep -c '[<].*HEAD' )

if [[ $DIFF -eq 0 ]]; then
    echo -e "\033[0;32mMerge conflict check passed!\033[0m"
    exit 0
fi

echo -en "\033[1;33mYou're about to commit an uncorrected merge conflict, is that what you intended? [y|n] \033[0m"
echo -en "\033[1m"
read -n 1 -r < /dev/tty
echo -en "\033[0m"

echo
if echo $REPLY | grep -E '^[Yy]$' > /dev/null; then
    exit 0 # Commit will execute
fi
exit 1 # Commit will not execute 