#!/bin/bash

PHPCBF=$( which phpcbf )

if [ ! -f "$PHPCBF" ]; then
    # PHPCBF isn't installed, skip.
    exit 0;
fi

echo -en "\033[1;33mWould you like to run PHPCBF? [y|n] \033[0m"
echo -en "\033[1m"
read -n 1 -r < /dev/tty
echo -en "\033[0m"
if echo $REPLY | grep -E '^[Yy]$' > /dev/null; then
    $PHPCBF
    exit $?
fi