#!/bin/bash

# If a local commit-msg hook is found, and is executable, run it.
if [ -x .git/hooks/commit-msg ]; then
    # Pass all of the parameters, unmodified, to the project hooks.
    # We do this so we don't interfere with anything that might be going on already.
    .git/hooks/commit-msg $1 || exit 1
fi