#!/bin/bash

# If a local pre-applypatch hook is found, and is executable, run it.
if [ -x .git/hooks/pre-applypatch ]; then
    # Pass all of the parameters, unmodified, to the project hooks.
    # We do this so we don't interfere with anything that might be going on already.
    .git/hooks/pre-applypatch || exit 1
fi