#!/bin/bash

# If a local prepare-commit-msg hook is found, and is executable, run it.
if [ -x .git/hooks/prepare-commit-msg ]; then
    # Pass all of the parameters, unmodified, to the project hooks.
    # We do this so we don't interfere with anything that might be going on already.
    .git/hooks/prepare-commit-msg $1 $2 $3 || exit 1
fi